-- data table
CREATE TABLE IF NOT EXISTS ELECTRICITY_CONSUMPTION_DATA_POINT_ENTITY
(
    ID SERIAL PRIMARY KEY,
    DEVICE_ID VARCHAR(255),
    LED_MILIS INTEGER,
    POINT_DATE TIMESTAMP
);


-- advanced config table
CREATE TABLE IF NOT EXISTS SERVER_CONFIG
(
    ID SERIAL PRIMARY KEY,
    DATA_FILTER_MILIS INTEGER,
    DEFAULT_TIME_WINDOW INTEGER,
    DEFAULT_TIME_ZONE_OFFSET INTEGER
);