-- data table
CREATE TABLE IF NOT EXISTS ELECTRICITY_CONSUMPTION_DATA_POINT_ENTITY
(
    ID SERIAL PRIMARY KEY,
    DEVICE_ID VARCHAR(255),
    LED_MILIS INTEGER,
    POINT_DATE TIMESTAMP
);

-- advanced config table
CREATE TABLE IF NOT EXISTS SERVER_CONFIG
(
    ID SERIAL PRIMARY KEY,
    DATA_FILTER_MILIS INTEGER,
    DEFAULT_TIME_WINDOW INTEGER
);


-- Default config values
INSERT INTO SERVER_CONFIG (DATA_FILTER_MILIS, DEFAULT_TIME_WINDOW)
SELECT 150, 15
WHERE (SELECT ID FROM SERVER_CONFIG LIMIT 1) IS NULL

